#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rr
Version  : 5.2.0
Release  : 6
URL      : https://github.com/mozilla/rr/archive/5.2.0.tar.gz
Source0  : https://github.com/mozilla/rr/archive/5.2.0.tar.gz
Summary  : Record and Replay framework: lightweight recording and deterministic debugging
Group    : Development/Tools
License  : BSD-2-Clause
Requires: rr-bin = %{version}-%{release}
Requires: rr-data = %{version}-%{release}
Requires: rr-lib = %{version}-%{release}
Requires: rr-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : capnproto-dev
BuildRequires : deprecated-pexpect-legacypython
BuildRequires : gdb-bin
BuildRequires : pkg-config
BuildRequires : python
BuildRequires : python3
Patch1: 0001-Remove-ucontext_t-rt_sigframe-from-kernel-abi.patch
Patch2: 0002-Use-C-14-CapnProto-0.70-requires-it.patch

%description
rr is a lightweight tool for recording and replaying execution of applications (trees of processes and threads).  For more information, please visit

http://rr-project.org

%package bin
Summary: bin components for the rr package.
Group: Binaries
Requires: rr-data = %{version}-%{release}
Requires: rr-license = %{version}-%{release}

%description bin
bin components for the rr package.


%package data
Summary: data components for the rr package.
Group: Data

%description data
data components for the rr package.


%package lib
Summary: lib components for the rr package.
Group: Libraries
Requires: rr-data = %{version}-%{release}
Requires: rr-license = %{version}-%{release}

%description lib
lib components for the rr package.


%package license
Summary: license components for the rr package.
Group: Default

%description license
license components for the rr package.


%prep
%setup -q -n rr-5.2.0
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554341704
mkdir -p clr-build
pushd clr-build
%cmake .. -Ddisable32bit=ON -DWILL_RUN_TESTS=OFF -DRR_BUILD_SHARED=ON -DBUILD_TESTS=OFF
make
popd

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1554341704
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rr
cp LICENSE %{buildroot}/usr/share/package-licenses/rr/LICENSE
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rr
/usr/bin/rr_exec_stub
/usr/bin/rr_page_32
/usr/bin/rr_page_32_replay
/usr/bin/rr_page_64
/usr/bin/rr_page_64_replay
/usr/bin/signal-rr-recording.sh

%files data
%defattr(-,root,root,-)
/usr/share/rr/32bit-avx.xml
/usr/share/rr/32bit-core.xml
/usr/share/rr/32bit-linux.xml
/usr/share/rr/32bit-sse.xml
/usr/share/rr/64bit-avx.xml
/usr/share/rr/64bit-core.xml
/usr/share/rr/64bit-linux.xml
/usr/share/rr/64bit-seg.xml
/usr/share/rr/64bit-sse.xml
/usr/share/rr/amd64-avx-linux.xml
/usr/share/rr/amd64-linux.xml
/usr/share/rr/i386-avx-linux.xml
/usr/share/rr/i386-linux.xml

%files lib
%defattr(-,root,root,-)
/usr/lib/librr.so
/usr/lib/rr/librrpreload.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rr/LICENSE
