#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rr
Version  : 5.4.0
Release  : 10
URL      : https://github.com/mozilla/rr/archive/5.4.0/rr-5.4.0.tar.gz
Source0  : https://github.com/mozilla/rr/archive/5.4.0/rr-5.4.0.tar.gz
Summary  : Lightweight tool for recording and replaying execution of applications (trees of processes and threads)
Group    : Development/Tools
License  : BSD-2-Clause
Requires: rr-bin = %{version}-%{release}
Requires: rr-data = %{version}-%{release}
Requires: rr-lib = %{version}-%{release}
Requires: rr-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : capnproto-dev
BuildRequires : gdb-bin
BuildRequires : pkg-config
BuildRequires : python3

%description
rr is a lightweight tool for recording and replaying execution of applications (trees of processes and threads).  For more information, please visit

http://rr-project.org

%package bin
Summary: bin components for the rr package.
Group: Binaries
Requires: rr-data = %{version}-%{release}
Requires: rr-license = %{version}-%{release}

%description bin
bin components for the rr package.


%package data
Summary: data components for the rr package.
Group: Data

%description data
data components for the rr package.


%package lib
Summary: lib components for the rr package.
Group: Libraries
Requires: rr-data = %{version}-%{release}
Requires: rr-license = %{version}-%{release}

%description lib
lib components for the rr package.


%package license
Summary: license components for the rr package.
Group: Default

%description license
license components for the rr package.


%prep
%setup -q -n rr-5.4.0
cd %{_builddir}/rr-5.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604539803
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -Ddisable32bit=ON \
-DWILL_RUN_TESTS=OFF \
-DRR_BUILD_SHARED=ON \
-DBUILD_TESTS=OFF
make
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1604539803
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rr
cp %{_builddir}/rr-5.4.0/LICENSE %{buildroot}/usr/share/package-licenses/rr/59884174935f26db20d5296805313b52834752e4
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rr
/usr/bin/rr-collect-symbols.py
/usr/bin/rr_exec_stub
/usr/bin/signal-rr-recording.sh

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/rr
/usr/share/rr/32bit-avx.xml
/usr/share/rr/32bit-core.xml
/usr/share/rr/32bit-linux.xml
/usr/share/rr/32bit-sse.xml
/usr/share/rr/64bit-avx.xml
/usr/share/rr/64bit-core.xml
/usr/share/rr/64bit-linux.xml
/usr/share/rr/64bit-seg.xml
/usr/share/rr/64bit-sse.xml
/usr/share/rr/aarch64-core.xml
/usr/share/rr/aarch64-fpu.xml
/usr/share/rr/aarch64-pauth.xml
/usr/share/rr/amd64-avx-linux.xml
/usr/share/rr/amd64-linux.xml
/usr/share/rr/i386-avx-linux.xml
/usr/share/rr/i386-linux.xml
/usr/share/rr/rr_page_32
/usr/share/rr/rr_page_32_replay
/usr/share/rr/rr_page_64
/usr/share/rr/rr_page_64_replay
/usr/share/rr/rr_page_arm64
/usr/share/rr/rr_page_arm64_replay
/usr/share/rr/src/preload/overrides.c
/usr/share/rr/src/preload/preload_interface.h
/usr/share/rr/src/preload/raw_syscall.S
/usr/share/rr/src/preload/syscall_hook.S
/usr/share/rr/src/preload/syscallbuf.c
/usr/share/rr/src/preload/syscallbuf.h

%files lib
%defattr(-,root,root,-)
/usr/lib64/librr.so
/usr/lib64/rr/librrpreload.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rr/59884174935f26db20d5296805313b52834752e4
